[tools]
node = "lts"
pnpm = "latest"

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
# postinstall = 'npx corepack enable'

[env]
_.path = ['./node_modules/.bin']

[tasks.pnpm-install]
description = 'Installs dependencies with pnpm'
run = 'pnpm install'
#sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
sources = ['pnpm-workspace.yaml', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.test]
description = 'Run test suite'
run = '''
cd packages/${1:-experiments} && pnpm test
'''
depends = ['pnpm-install']

[tasks.docker_build]
run = 'docker build -t debian-mise .'

[tasks.docker_run]
depends = ['docker_build']
run = '''
docker run -it --rm debian-mise
'''